version: "3"
services:
  rallly_db:
    image: postgres:14.2
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${ADMIN_PASSWORD}
      - POSTGRES_DB=db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rallly:
    image: lukevella/rallly:${SOFTWARE_VERSION_TAG}
    restart: always
    depends_on:
      rallly_db:
        condition: service_healthy
    ports:
      - 172.17.0.1:8934:3000
    environment:
      - DATABASE_URL=postgres://postgres:${ADMIN_PASSWORD}@rallly_db:5432/db
    env_file:
      - ./.env